apiVersion: v1
kind: Pod
metadata:
  name: {{ .Values.serviceName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appLabel }}
    deployment_id: {{ .Values.deploymentId | quote }}
spec:
  volumes:
    - name: jfs-data
      persistentVolumeClaim:
        claimName: {{ .Values.pvcName }}
  containers:
    - name: server
      image: {{ .Values.image }}
      {{- if .Values.command }}
      command:
      {{- range .Values.command }}
        - {{ . | quote }}
      {{- end }}
      {{- end }}
      {{- if .Values.arguments }}
      args:
      {{- range .Values.arguments }}
        - {{ . | quote }}
      {{- end }}
      {{- end }}
      volumeMounts:
        - name: jfs-data
          mountPath: {{ .Values.mountPath }}
          readOnly: false
      {{- if .Values.envs }}
      env:
      {{- range $key, $value := .Values.envs }}
        - name: {{ $key }}
          value: {{ $value | quote }}
      {{- end }}
      {{- end }}
      resources:
        requests:
          cpu: {{ .Values.cpuRequest | quote }}m
          memory: "{{ .Values.memoryRequest }}Gi"
        limits:
          cpu: {{ .Values.cpuLimit | quote }}m
          memory: "{{ .Values.memoryLimit }}Gi"
          {{- if and .Values.gpuLimit (gt (int .Values.gpuLimit) 0) }}
          nvidia.com/gpu: {{ .Values.gpuLimit | quote }}
          {{- end }}
