apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.pvName }}
  labels:
    user: {{ .Values.username }}
    deployment_id: {{ .Values.deploymentId | quote }}
spec:
  capacity:
    storage: {{ .Values.storageSize }}
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.storageClass }}
  csi:
    driver: csi.juicefs.com
    volumeHandle: {{ .Values.volumeHandle }}
    volumeAttributes:
      subdir: /{{ .Values.username }}
    nodePublishSecretRef:
      name: {{ .Values.secretName }}
      namespace: {{ .Values.namespace }}
