apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvcName }}
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.storageSize }}
  storageClassName: {{ .Values.storageClass }}
  selector:
    matchLabels:
      user: {{ .Values.username }}
      deployment_id: {{ .Values.deploymentId | quote }}
